services:
  pg_db:
    image: postgres:15-alpine
    container_name: pg_database
    # restart: unless-stopped  # Auto-restart on crash or reboot
    ports:
      - '5432:5432'  # Host:Container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent db storage
      - ./init-scripts:/docker-entrypoint-initdb.d  # Auto-run scripts on start
      - ./input-data:/data
      - ./etl-scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local