version: '3'
services:
  pg_database:
    image: 'postgres:15'
    restart: unless-stopped  # Auto-restart on crash or reboot
    ports:
      - 5432:5432  # Host:Container
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent db storage
      - ./init-scripts:/docker-entrypoint-initdb.d  # Auto-run scripts on start
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local